# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hawthorn Tech Solutions Ltd
tagline:          'Your Technology Solutions'
description:      'Monolith to micro services; webservices in java, golang, python; Android; javascript; kotlin; kafka; C++'
url:              https://hawthorntechsolutions.co.uk

author:
  name:           'Ankur Agarwal'
  url:            https://twitter.com/ankur_a22

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ankur22/hawthorn-tech-solutions
